### ISSUE TITLE
Void jar compatibility

### ISSUE THREAD

**Issue by UnixRonin** [Jezza/Thaumic-Pipes#11]
Jezza, I think I found another bug, more minor this time.  Void jars and Thaumic Pipes sort of work together, but with a few glitches.  A labelled void jar is supposed to have more suction than an unlabelled warded jar, but less than a labelled one, so matching typed essentia will flow from a source into a labelled void jar in preference to an unlabelled jar, but will not be drawn out of a labelled jar into a labelled void jar.
In practice what seems to be happening is that when connected via thaumic pipes, the labelled warded jar and a labelled void jar behave as though they have the same suction, and they try to equalize the quantity of essentia between them.
What makes this even odder is if you connect a labelled warded jar and a labelled void jar via their tops by three essentia tubes above them, and ALSO by a single Thaumic Pipe directly between their adjacent sides.  Via the essentia tubes, essentia flows from the void jar to the warded jar because its suction is higher; but the thaumic pipe tries to equalize the levels in the two jars.  So you get a non-stop loop flow set up, with essentia flowing from the void jar to the warded jar via the essentia tubes, then back through the thaumic pipe into the void jar.

**Comment by Jezza** [comment]
That's actually pretty funny...
On a more serious note, I'm already fairly deep into 1.2.00, so the fix will come in that version.
Sorry for the inconvenience.
ETA on 1.2.00: Probably tomorrow.

**Comment by UnixRonin** [comment]
No rush.  :)  Just discovered it when I started messing with void jars.
Also, in further testing, a labelled void jar should draw new essentia into itself, even if already full, rather than start a new jar.  But in practice when I try it, when the void jar fills, a new jar is started instead of the void jar destroying the excess essentia.

**Comment by Jezza** [comment]
Yeah, I treat void jars as the same to normal jars.
1.2.00 is going to solve a lot of these silly things that I've overlooked.
:D

**Comment by Jezza** [comment]
Apologies for the LONG wait. :(
Life doesn't always agree with what I want to do... :P
But yes, 1.2.00 is probably going to be coming out in the coming day or two.
I've fixed all these little issues as well as added something special.

**Comment by Jezza** [comment]
1.2.00 is released! It was released a while ago, but yes, enjoy. Should fix this. ;)
