### ISSUE TITLE
Viewing Essentia and other things

### ISSUE THREAD

**Issue by Fortist** [Jezza/Thaumic-Pipes#5]
Something needs to be added:
Either a way to view how much and what essentia is currently in the pipes
and/or
The pipes shouldnt instantly pull from Alembics

Was just testing with something that was heavy in aspects and it filled the jars with the most first, and when putting more jars connecting with the pipes they ALL take the same kind of essentia
IE: 12 Metal, 4 Air, 4 Order
Connect 3 jars to the pipes
Metal would spread to all 3 jars first

**Comment by Jezza** [comment]
There are now particle effects to show what essentia is going where. ;)
