### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by kurokuno** [Jezza/Thaumic-Pipes#8]
18:22:44 cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
18:22:44 at cpw.mods.fml.common.LoadController.transition(LoadController.java:162) ~[LoadController.class:?]
18:22:44 at cpw.mods.fml.common.Loader.initializeMods(Loader.java:695) ~[Loader.class:?]
18:22:44 at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97) ~[FMLServerHandler.class:?]
18:22:44 at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:319) ~[FMLCommonHandler.class:?]
18:22:44 at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:210) ~[lt.class:?]
18:22:44 at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
18:22:44 at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
18:22:44 Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
18:22:44 at me.jezza.thaumicpipes.common.research.ModResearch.initResearch(ModResearch.java:29) ~[ModResearch.class:?]
18:22:44 at me.jezza.thaumicpipes.common.research.ModResearch.init(ModResearch.java:22) ~[ModResearch.class:?]
18:22:44 at me.jezza.thaumicpipes.ThaumicPipes.postInit(ThaumicPipes.java:57) ~[ThaumicPipes.class:?]
18:22:44 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_05]
18:22:44 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_05]
18:22:44 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_05]
18:22:44 at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_05]
18:22:44 at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513) ~[FMLModContainer.class:?]
18:22:44 at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
18:22:44 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_05]
18:22:44 at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_05]
18:22:44 at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.7.10.jar:?]
18:22:44 at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.7.10.jar:?]
18:22:44 at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.7.10.jar:?]
18:22:44 at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.7.10.jar:?]
18:22:44 at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.7.10.jar:?]
18:22:44 at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208) ~[LoadController.class:?]
18:22:44 at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187) ~[LoadController.class:?]
18:22:44 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_05]
18:22:44 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_05]
18:22:44 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_05]
18:22:44 at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_05]
18:22:44 at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.7.10.jar:?]
18:22:44 at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.7.10.jar:?]
18:22:44 at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.7.10.jar:?]
18:22:44 at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.7.10.jar:?]
18:22:44 at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.7.10.jar:?]
18:22:44 at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118) ~[LoadController.class:?]
18:22:44 at cpw.mods.fml.common.Loader.initializeMods(Loader.java:694) ~[Loader.class:?]
18:22:44 ... 5 more
18:22:44 Caused by: java.lang.ClassNotFoundException: net.minecraft.client.resources.I18n
18:22:44 at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.11.jar:?]
18:22:44 at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_05]
18:22:44 at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_05]
18:22:44 at me.jezza.thaumicpipes.common.research.ModResearch.initResearch(ModResearch.java:29) ~[ModResearch.class:?]
18:22:44 at me.jezza.thaumicpipes.common.research.ModResearch.init(ModResearch.java:22) ~[ModResearch.class:?]
18:22:44 at me.jezza.thaumicpipes.ThaumicPipes.postInit(ThaumicPipes.java:57) ~[ThaumicPipes.class:?]
18:22:44 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_05]
18:22:44 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_05]
18:22:44 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_05]
18:22:44 at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_05]
18:22:44 at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513) ~[FMLModContainer.class:?]
18:22:44 at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
18:22:44 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_05]
18:22:44 at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_05]
18:22:44 at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.7.10.jar:?]
18:22:44 at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.7.10.jar:?]
18:22:44 at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.7.10.jar:?]
18:22:44 at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.7.10.jar:?]
18:22:44 at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.7.10.jar:?]
18:22:44 at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208) ~[LoadController.class:?]
18:22:44 at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187) ~[LoadController.class:?]
18:22:44 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_05]
18:22:44 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_05]
18:22:44 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_05]
18:22:44 at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_05]
18:22:44 at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.7.10.jar:?]
18:22:44 at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.7.10.jar:?]
18:22:44 at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.7.10.jar:?]
18:22:44 at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.7.10.jar:?]
18:22:44 at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.7.10.jar:?]
18:22:44 at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118) ~[LoadController.class:?]
18:22:44 at cpw.mods.fml.common.Loader.initializeMods(Loader.java:694) ~[Loader.class:?]
18:22:44 ... 5 more
18:22:44 Caused by: java.lang.NullPointerException

**Comment by Jezza** [comment]
1.2.00 fixes all of these issues. (Not released yet. :P)
The only thing that it requires is that if mods want to use ThaumicPipes, they have to support it.
I'll offer an insanely easy API that they can use, so you'll probably have to send them a message when I release it. Probably by tomorrow. :P

**Comment by Jezza** [comment]
This is fixed in 1.2.00! Or at least, it should be. Give me a shout it if it isn't. ;)
